apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: aif22-3
  # The name of the profile, which will also be used as the namespace name
spec:
  # Owner of the profile
  owner:
    kind: User  # Can be 'User' or 'ServiceAccount'
    name: aif22-3@paf-iast  # The user's email or ServiceAccount name
  # Optional: Resource quota for the namespace
  resourceQuotaSpec:
    hard:
      cpu: "5"
      memory: 5Gi
      requests.aliyun.com/gpu-mem: "5"
      requests.aliyun.com/gpu-count: "0"
      requests.storage: 10Gi